//
//  Synopsis-Private.h
//  Synopsis-Framework
//
//  Created by vade on 12/16/19.
//  Copyright © 2019 v002. All rights reserved.
//

#include "TargetConditionals.h"
#import <Foundation/Foundation.h>

// Metadata Type Strings:
extern NSString* const kSynopsisMetadataTypeGlobal;
extern NSString* const kSynopsisMetadataTypeSample;

// Metadata Identifier Strings:
extern NSString* const kSynopsisMetadataIdentifierGlobalVisualDescription;
extern NSString* const kSynopsisMetadataIdentifierVisualEmbedding;
extern NSString* const kSynopsisMetadataIdentifierVisualProbabilities;
extern NSString* const kSynopsisMetadataIdentifierVisualHistogram;
extern NSString* const kSynopsisMetadataIdentifierVisualDominantColors;
extern NSString* const kSynopsisMetadataIdentifierTimeSeriesVisualEmbedding;
extern NSString* const kSynopsisMetadataIdentifierTimeSeriesVisualProbabilities;
extern NSString* const kSynopsisMetadataIdentifierTimeSeriesVisualHistogram;
extern NSString* const kSynopsisMetadataIdentifierTimeSeriesVisualDominantColors;


#pragma mark - CinemaNet Groups, Concepts and Labels
    
extern NSString* const kCinemaNetClassLabelColorKeyBlueKey;
extern NSString* const kCinemaNetClassLabelColorKeyGreenKey;
extern NSString* const kCinemaNetClassLabelColorKeyLumaKey;
extern NSString* const kCinemaNetClassLabelColorKeyMatteKey;
extern NSString* const kCinemaNetClassLabelColorKeyNaKey;

extern NSString* const kCinemaNetClassLabelColorSaturationDesaturatedKey;
extern NSString* const kCinemaNetClassLabelColorSaturationNeutralKey;
extern NSString* const kCinemaNetClassLabelColorSaturationPastelKey;
extern NSString* const kCinemaNetClassLabelColorSaturationSaturatedKey;

extern NSString* const kCinemaNetClassLabelColorTheoryAnalagousKey;
extern NSString* const kCinemaNetClassLabelColorTheoryComplementaryKey;
extern NSString* const kCinemaNetClassLabelColorTheoryMonochromeKey;

extern NSString* const kCinemaNetClassLabelColorTonesBlackWhiteKey;
extern NSString* const kCinemaNetClassLabelColorTonesCoolKey;
extern NSString* const kCinemaNetClassLabelColorTonesWarmKey;
    
extern NSString* const kCinemaNetClassLabelShotAngleAerialKey;
extern NSString* const kCinemaNetClassLabelShotAngleEyeLevelKey;
extern NSString* const kCinemaNetClassLabelShotAngleHighKey;
extern NSString* const kCinemaNetClassLabelShotAngleLowKey;
extern NSString* const kCinemaNetClassLabelShotAngleNaKey;

extern NSString* const kCinemaNetClassLabelShotFocusDeepKey;
extern NSString* const kCinemaNetClassLabelShotFocusOutKey;
extern NSString* const kCinemaNetClassLabelShotFocusShallowKey;
extern NSString* const kCinemaNetClassLabelShotFocusNaKey;

extern NSString* const kCinemaNetClassLabelShotFramingCloseupKey;
extern NSString* const kCinemaNetClassLabelShotFramingExtremeCloseupKey;
extern NSString* const kCinemaNetClassLabelShotFramingExtremeLongKey;
extern NSString* const kCinemaNetClassLabelShotFramingLongKey;
extern NSString* const kCinemaNetClassLabelShotFramingMediumKey;
extern NSString* const kCinemaNetClassLabelShotFramingNaKey;

extern NSString* const kCinemaNetClassLabelShotLevelLevelKey;
extern NSString* const kCinemaNetClassLabelShotLevelTiltedKey;
extern NSString* const kCinemaNetClassLabelShotLevelNaKey;

extern NSString* const kCinemaNetClassLabelShotLightingHardKey;
extern NSString* const kCinemaNetClassLabelShotLightingKeyHighKeyhighKey;
extern NSString* const kCinemaNetClassLabelShotLightingKeyLowKeylowKey;
extern NSString* const kCinemaNetClassLabelShotLightingNeutralKey;
extern NSString* const kCinemaNetClassLabelShotLightingSilhouetteKey;
extern NSString* const kCinemaNetClassLabelShotLightingSoftKey;
extern NSString* const kCinemaNetClassLabelShotLightingNaKey;

extern NSString* const kCinemaNetClassLabelShotLocationExteriorKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorNatureBeachKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorNatureCanyonKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorNatureCaveKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorNatureDesertKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorNatureForestKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorNatureGlacierKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorNatureLakeKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorNatureMountainsKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorNatureOceanKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorNaturePlainsKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorNaturePolarKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorNatureRiverKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorNatureSkyKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorNatureSpaceKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorNatureWetlandsKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorSettlementCityKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorSettlementSuburbKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorSettlementTownKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureBridgeKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureBuildingAirportKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureBuildingAutoBodyKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureBuildingCastleKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureBuildingHospitalKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureBuildingHouseofworshipKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureBuildingLibraryKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureBuildingMallKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureBuildingOfficeKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureBuildingResidenceApartmentKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureBuildingResidenceHouseKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureBuildingResidenceMansionKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureBuildingResidenceMonasteryKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureBuildingResidencePalaceKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureBuildingRestaurantKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureBuildingSchoolKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureBuildingSkyscraperKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureBuildingStadiumKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureBuildingStationGasKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureBuildingStationSubwayKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureBuildingStationTrainKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureBuildingStoreKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureBuildingTheaterKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureBuildingWarehouseKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureBusStopKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureFarmKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureIndustrialKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureParkKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureParkinglotKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructurePierKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructurePlaygroundKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructurePortKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureRoadKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureRuinsKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureSidewalkKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureTunnelKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureVehicleAirplaneKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureVehicleBicycleKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureVehicleBoatKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureVehicleBusKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureVehicleCarKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureVehicleHelicopterKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureVehicleMotorcycleKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureVehicleSpacecraftKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureVehicleTrainKey;
extern NSString* const kCinemaNetClassLabelShotLocationExteriorStructureVehicleTruckKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorNatureCaveKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingAirportKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingArenaKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingAuditoriumKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingAutoRepairShopKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingBarKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingBarnKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingCafeKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingCafeteriaKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingCommandCenterKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingCryptKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingDancefloorKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingDungeonKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingElevatorKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingFactoryKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingFoyerKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingGymKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingHallwayKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingHospitalKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingHouseofworshipKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingLobbyKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingMallKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingOfficeKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingOfficeCubicleKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingOpenOfficeKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingPrisonKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingRestaurantKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingRoomBathKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingRoomBedKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingRoomClassKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingRoomClosetKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingRoomConferenceKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingRoomCourtKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingRoomDiningKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingRoomKitchenKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingRoomKitchenCommercialKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingRoomLivingKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingRoomStudyKey ;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingRoomThroneKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingStageKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingStairwellKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingStationBusKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingStationFireKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingStationPoliceKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingStationSubwayKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingStationTrainKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingStoreKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingStoreAisleKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingStoreCheckoutKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureBuildingWarehouseKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureVehicleAirplaneCabinKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureVehicleAirplaneCockpitKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureVehicleBoatKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureVehicleBusKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureVehicleCarKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureVehicleHelicopterKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureVehicleSpacecraftKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureVehicleSubwayKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureVehicleTrainKey;
extern NSString* const kCinemaNetClassLabelShotLocationInteriorStructureVehicleTruckKey;
extern NSString* const kCinemaNetClassLabelShotLocationNaKey;

extern NSString* const kCinemaNetClassLabelShotSubjectAnimalKey;
extern NSString* const kCinemaNetClassLabelShotSubjectLocationKey;
extern NSString* const kCinemaNetClassLabelShotSubjectObjectKey;
extern NSString* const kCinemaNetClassLabelShotSubjectPersonKey;
extern NSString* const kCinemaNetClassLabelShotSubjectPersonBodyKey;
extern NSString* const kCinemaNetClassLabelShotSubjectPersonFaceKey;
extern NSString* const kCinemaNetClassLabelShotSubjectPersonFeetKey;
extern NSString* const kCinemaNetClassLabelShotSubjectPersonHandsKey;
extern NSString* const kCinemaNetClassLabelShotSubjectTextKey;
extern NSString* const kCinemaNetClassLabelShotSubjectNaKey;

extern NSString* const kCinemaNetClassLabelShotTimeofdayDayKey;
extern NSString* const kCinemaNetClassLabelShotTimeofdayNightKey;
extern NSString* const kCinemaNetClassLabelShotTimeofdayTwilightKey;
extern NSString* const kCinemaNetClassLabelShotTimeofdayNaKey;

extern NSString* const kCinemaNetClassLabelShotTypeMasterKey;
extern NSString* const kCinemaNetClassLabelShotTypeOvertheshoulderKey;
extern NSString* const kCinemaNetClassLabelShotTypePortraitKey;
extern NSString* const kCinemaNetClassLabelShotTypeTwoshotKey;
extern NSString* const kCinemaNetClassLabelShotTypeNaKey;

extern NSString* const kCinemaNetClassLabelTextureBandedKey;
extern NSString* const kCinemaNetClassLabelTextureBlotchyKey;
extern NSString* const kCinemaNetClassLabelTextureBraidedKey;
extern NSString* const kCinemaNetClassLabelTextureBubblyKey;
extern NSString* const kCinemaNetClassLabelTextureBumpyKey;
extern NSString* const kCinemaNetClassLabelTextureChequeredKey;
extern NSString* const kCinemaNetClassLabelTextureCobwebbedKey;
extern NSString* const kCinemaNetClassLabelTextureCrackedKey;
extern NSString* const kCinemaNetClassLabelTextureCrosshatchedKey;
extern NSString* const kCinemaNetClassLabelTextureCrystallineKey;
extern NSString* const kCinemaNetClassLabelTextureDottedKey;
extern NSString* const kCinemaNetClassLabelTextureFibrousKey;
extern NSString* const kCinemaNetClassLabelTextureFleckedKey;
extern NSString* const kCinemaNetClassLabelTextureFrillyKey;
extern NSString* const kCinemaNetClassLabelTextureGauzyKey;
extern NSString* const kCinemaNetClassLabelTextureGridKey;
extern NSString* const kCinemaNetClassLabelTextureGroovedKey;
extern NSString* const kCinemaNetClassLabelTextureHoneycombedKey;
extern NSString* const kCinemaNetClassLabelTextureInterlacedKey;
extern NSString* const kCinemaNetClassLabelTextureKnittedKey;
extern NSString* const kCinemaNetClassLabelTextureLacelikeKey;
extern NSString* const kCinemaNetClassLabelTextureLinedKey;
extern NSString* const kCinemaNetClassLabelTextureMarbledKey;
extern NSString* const kCinemaNetClassLabelTextureMattedKey;
extern NSString* const kCinemaNetClassLabelTextureMeshedKey;
extern NSString* const kCinemaNetClassLabelTexturePaisleyKey;
extern NSString* const kCinemaNetClassLabelTexturePerforatedKey;
extern NSString* const kCinemaNetClassLabelTexturePittedKey;
extern NSString* const kCinemaNetClassLabelTexturePleatedKey;
extern NSString* const kCinemaNetClassLabelTexturePorousKey;
extern NSString* const kCinemaNetClassLabelTexturePotholedKey;
extern NSString* const kCinemaNetClassLabelTextureScalyKey;
extern NSString* const kCinemaNetClassLabelTextureSmearedKey;
extern NSString* const kCinemaNetClassLabelTextureSpiralledKey;
extern NSString* const kCinemaNetClassLabelTextureSprinkledKey;
extern NSString* const kCinemaNetClassLabelTextureStainedKey;
extern NSString* const kCinemaNetClassLabelTextureStratifiedKey;
extern NSString* const kCinemaNetClassLabelTextureStripedKey;
extern NSString* const kCinemaNetClassLabelTextureStuddedKey;
extern NSString* const kCinemaNetClassLabelTextureSwirlyKey;
extern NSString* const kCinemaNetClassLabelTextureVeinedKey;
extern NSString* const kCinemaNetClassLabelTextureWaffledKey;
extern NSString* const kCinemaNetClassLabelTextureWovenKey;
extern NSString* const kCinemaNetClassLabelTextureWrinkledKey;
extern NSString* const kCinemaNetClassLabelTextureZigzaggedKey;
